# Copyright 2017-2020 VMware, Inc.  All rights reserved
#
# The BSD-2 license (the "License") set forth below applies to all
# parts of the NSX-T SDK Sample Code project.  You may not use this
# file except in compliance with the License.
# BSD-2 License
# Redistribution and use in source and binary forms, with or
# without modification, are permitted provided that the following
# conditions are met:
#     Redistributions of source code must retain the above
#     copyright notice, this list of conditions and the
#     following disclaimer.
#     Redistributions in binary form must reproduce the above
#     copyright notice, this list of conditions and the
#     following disclaimer in the documentation and/or other
#     materials provided with the distribution.
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
# USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
# AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
---
- hosts: localhost
  become: no
  vars:
      nsx_manager: '10.221.109.5'
      nsx_username: 'admin'
      nsx_password: 'VMware1!VMware1!'
      validate_certs: 'false'
  tasks:
    - name: Security Policy ANS-Ops
      vmware.ansible_for_nsxt.nsxt_policy_security_policy:
        hostname: "{{ nsx_manager }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        state: "{{ state }}"
        display_name: "ANS-Ops"
        domain_id: "default"
        category: "Infrastructure"
        rules:
          - action: "REJECT"
            display_name: "Allow-SSH"
            source_groups: ["ANY"]
            destination_groups: ["/infra/domains/default/groups/ANS-all-vms"]
            services: ["/infra/services/SSH"]
          - action: "ALLOW"
            display_name: "Allow-ICMP"
            source_groups: ["ANY"]
            destination_groups: ["/infra/domains/default/groups/ANS-all-vms"]
            services: ["/infra/services/ICMP-ALL"]

    - name: Security Policy ANS-Allow-SQl
      vmware.ansible_for_nsxt.nsxt_policy_security_policy:
        hostname: "{{ nsx_manager }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        state: "{{ state }}"
        display_name: "ANS-Allow-SQL"
        domain_id: "default"
        category: "Application"
        rules:
          - action: "ALLOW"
            display_name: "allow-mysql"
            source_groups: ["ANY"]
            destination_groups: ["/infra/domains/default/groups/ANS-db-vms"]
            services: ["/infra/services/MySQL"]

    - name: Security Policy ANS-Allow-HTTP
      vmware.ansible_for_nsxt.nsxt_policy_security_policy:
        hostname: "{{ nsx_manager }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        state: "{{ state }}"
        display_name: "ANS-Allow-HTTP"
        domain_id: "default"
        category: "Application"
        rules:
          - action: "ALLOW"
            display_name: "allow-80-443"
            source_groups: ["ANY"]
            destination_groups: ["/infra/domains/default/groups/ANS-web-vms"]
            services: ["/infra/services/HTTP", "/infra/services/HTTPS"]
